[FIX] website_blog: prevent error when no blog posts are published
blog.blog has no attribute post_date therefore as a fallback we need to use the
write_date of the blog.blog element when no blog.posts are published.

this prevents the following error:
```
File "/opt/odoo/custom/src/odoo/odoo/addons/base/ir/ir_qweb/qweb.py", line 353, in _compiled_fn
    raise QWebException("Error to render compiling AST", e, path, node and etree.tostring(node[0], encoding='unicode'), name)
odoo.addons.base.ir.ir_qweb.qweb.QWebException: 'blog.blog' object has no attribute 'post_date'
Traceback (most recent call last):
  File "/opt/odoo/custom/src/odoo/odoo/addons/base/ir/ir_qweb/qweb.py", line 346, in _compiled_fn
    return compiled(self, append, new, options, log)
  File "<template>", line 1, in template_1400_458
AttributeError: 'blog.blog' object has no attribute 'post_date'
```

closes odoo/odoo#54116

Signed-off-by: Jérémy Kersten (jke) <jke@openerp.com>